services:
  backend:
    build: ./backend/
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend/:/app/
    ports:
      - 8000:8000
    depends_on:
      - db
  frontend:
    build: ./frontend/
    command: uv run uvicorn main:app --host 0.0.0.0 --port 3000 --reload
    volumes:
      - ./frontend/:/app/
    ports:
      - 3000:3000
    # depends_on:
    #   - db
  db:
    image: postgres:16.2
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: pomodoro

  # cache:
  #   image: redis:7.2.4-alpine
  #   ports:
  #     - '6379:6379'
